### ISSUE TITLE
declare FUUID java.io.Serializable?

### ISSUE THREAD

**Issue by drobert** [ChristopherDavenport/fuuid#183]
Regardless of the lameness of java serialization, there some frameworks and libraries that rely on it. (My current example is using FUUID in Apache Beam.)

It would be useful if FUUID declared itself `java.io.Serializable`, and likely delegated its serialization to the underlying UUID. I realize the implementation of this would be Unsafe, but that's mostly the nature of java serialization anyway I suppose.

**Comment by ChristopherDavenport** [comment]
So my baseline is a dislike for the idea, hence a really late response that I should have written sooner. My apologies. However, I am not in the realm where I ever use `java.io.Serializable` so I will happily take input from others, if others think this is important enough its not a hill I will die on.

**Comment by morgen-peschke** [comment]
Unfortunately, ScalaTest uses Java serialization, and ScalaCheck's integration includes the generated values in the ScalaTest reports, which causes trouble whenever an `FUUID` is parted of a generated value.

```
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 3),ExceptionInInitializerError was thrown during property evaluation.
...
java.io.NotSerializableException: io.chrisdavenport.fuuid.FUUID
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
```

**Comment by zarthross** [comment]
I believe this can be closed now? @ChristopherDavenport
