### ISSUE TITLE
Numberformatexception can escape your `fromString` function

### ISSUE THREAD

**Issue by jmcardon** [ChristopherDavenport/fuuid#38]
```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

import java.util.UUID
UUID.fromString("2630147c-4a18-4866-9bbd-b2d89acef83z")

// Exiting paste mode, now interpreting.

java.lang.NumberFormatException: For input string: "b2d89acef83z"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Long.parseLong(Long.java:589)
  at java.lang.Long.valueOf(Long.java:776)
  at java.lang.Long.decode(Long.java:928)
  at java.util.UUID.fromString(UUID.java:206)
  ... 44 elided
```

this makes the `fromEither` function impure

**Comment by ChristopherDavenport** [comment]
Thank you for this. :+1: Will get a fix started right away.
